name: Hello_world

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello and Welcome to the GH-200 session!!!"

      - name: Copy code
        uses: actions/checkout@v5

      - name: List files
        run: ls -la

      - name: Install Package
        run: |
          sudo apt-get install -y figlet
          figlet "GH-200 COHACK"
          echo "-----------------------------"
          figlet -f digital "GitHub Actions
